# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-06 19:17
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, unique=True, verbose_name='Channel name')),
            ],
            options={
                'verbose_name_plural': 'Channels',
                'verbose_name': 'Channel',
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ts', models.IntegerField(verbose_name='Start timestamp')),
                ('end_ts', models.IntegerField(verbose_name='End timestamp')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Channel')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200, verbose_name='Topic')),
                ('count', models.IntegerField()),
                ('score', models.FloatField()),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Segment')),
            ],
        ),
        migrations.AddField(
            model_name='audience',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Channel'),
        ),
        migrations.AlterUniqueTogether(
            name='audience',
            unique_together=set([('timestamp', 'channel')]),
        ),
    ]
